### ISSUE TITLE
Nodes in state `draining` show up as usable

### ISSUE THREAD

**Issue by RyanrDavies** [cdt-data-science/cluster-scripts#20]
Nodes with state `draining` are counted as usable in `gpu-usage`, `free-gpus`, etc but do not accept jobs, so should not be counted as usable.

**Comment by RyanrDavies** [comment]
It looks like this is because nodes in state `draining` are included when using the filter `alloc`. It's not clear from the man page for `sinfo` whether this is correct or not -- there is also a filter `drain` which returns nodes in state `draining`, so I wouldn't have expected `draining` to fall under `alloc` as well.

**Comment by RyanrDavies** [comment]
Actually, I think this may be because there are still jobs running on the node, so it counts as allocated.

**Comment by JamesOwers** [comment]
Let's close this for now, I think you cracked it
