### ISSUE TITLE
Wrong commands in the example

### ISSUE THREAD

**Issue by mpatsis** [cdt-data-science/cluster-scripts#21]
In the example all the cluster scripts are run like: ./_script_ e.g., ./free-gpus
I think that the correct command is instead: _script_ e.g., free-gpus 
./free-gpus will not work for me unless I have cd'ed in the cluster scripts folder.

**Comment by JamesOwers** [comment]
I agree, I'm going to fix this in the next pr

**Comment by OpeyemiOsakuade** [comment]
"free-gpus" does not work for me but "./free-gpu" does
